// This file is generated by build_src/gen.rs
use crate::info::EpDirection;
use crate::info::EpInfo;
pub struct UsbInstance;
impl crate::MusbInstance for UsbInstance {
    fn regs() -> crate::regs::Usb {
        unsafe { crate::regs::Usb::from_ptr((0x40005c00) as _ ) }
    }
}
pub const ENDPOINTS: [EpInfo; 6] = [
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 64,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 64,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 128,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 128,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 128,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 64,
    },
];
