// This file is generated by build_src/gen.rs
use crate::info::EpDirection;
use crate::info::EpInfo;
pub const ENDPOINTS: [EpInfo; 8] = [
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 2048,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 2048,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 2048,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 2048,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 2048,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 2048,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 2048,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 2048,
    },
];
pub const TOTAL_FIFO_SIZE: u16 = 2048;
