// This file is generated by build_src/gen.rs
use crate::info::EpDirection;
use crate::info::EpInfo;
pub const ENDPOINTS: [EpInfo; 1] = [
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size: 64,
    },
];
pub const TOTAL_FIFO_SIZE: u16 = 9999;
