use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::Path;

use crate::config::AppConfig;
use crate::layout::Layout;

/// Generate all linker scripts into `out_dir`.
pub fn generate(
    config: &AppConfig,
    layout: &Layout,
    out_dir: &Path,
) -> Result<(), LinkerError> {
    std::fs::create_dir_all(out_dir).map_err(LinkerError::Io)?;

    // Each task gets its own subdirectory so `memory.x` doesn't collide.

    // Bootloader (optional)
    if let Some(bl) = &config.bootloader {
        let bl_dir = out_dir.join("bootloader");
        std::fs::create_dir_all(&bl_dir).map_err(LinkerError::Io)?;
        write_file(&bl_dir, "memory.x", &build_memory_x("bootloader", &bl.regions, layout))?;
        write_file(&bl_dir, "link.x", &bootloader_link_script())?;
    }

    // Kernel
    let kernel_dir = out_dir.join("kernel");
    std::fs::create_dir_all(&kernel_dir).map_err(LinkerError::Io)?;
    write_file(&kernel_dir, "memory.x", &build_memory_x("kernel", &config.kernel.regions, layout))?;
    write_file(&kernel_dir, "link.x", &kernel_link_script())?;
    write_file(&kernel_dir, "device.x", &kernel_device_x(config))?;

    // Tasks
    let tasks = crate::layout::collect_tasks(config);
    for crate_name in tasks.keys() {
        let task = tasks[crate_name];
        let task_dir = out_dir.join(crate_name);
        std::fs::create_dir_all(&task_dir).map_err(LinkerError::Io)?;

        let custom_regions: Vec<&str> = task
            .regions
            .keys()
            .filter(|n| !matches!(n.as_str(), "code" | "data" | "stack"))
            .map(|s| s.as_str())
            .collect();

        write_file(&task_dir, "memory.x", &build_memory_x(crate_name, &task.regions, layout))?;
        write_file(&task_dir, "link.x", &task_link_script(&custom_regions))?;
    }

    Ok(())
}

/// Build a `memory.x` for a given owner.
/// Only includes regions that have CPU-mapped allocations.
fn build_memory_x(
    owner: &str,
    regions: &BTreeMap<String, crate::config::RegionRequest>,
    layout: &Layout,
) -> String {
    let mut out = String::from("MEMORY\n{\n");

    for (region_name, _req) in regions {
        let key = (owner.to_string(), region_name.clone());

        let linker_name: String = match region_name.as_str() {
            "code" => "FLASH".to_string(),
            "data" => "RAM".to_string(),
            "stack" => "STACK".to_string(),
            other => other.to_uppercase(),
        };

        let attrs = match region_name.as_str() {
            "code" => "rx",
            "stack" => "rw",
            _ => "rw",
        };

        if let Some(alloc) = layout.placed.get(&key) {
            writeln!(
                out,
                "  {linker_name} ({attrs}) : ORIGIN = {:#010x}, LENGTH = {:#x}",
                alloc.base, alloc.size
            )
            .unwrap();
        } else if let Some(req) = layout.deferred.get(&key) {
            // Deferred — use the remaining space after all placed regions in the same place.
            let offset = req.place.offset.unwrap_or(0);
            if let Some(mapping) = req.place.mappings.first() {
                let place_base = mapping.address + offset;
                let place_end = place_base + req.place.size;

                // Find the highest end address of any placed region in this same place
                let highest_used = layout.placed.values()
                    .filter(|a| a.base >= place_base && a.base < place_end)
                    .map(|a| a.base + a.size)
                    .max()
                    .unwrap_or(place_base);

                let deferred_origin = highest_used;
                let deferred_length = place_end.saturating_sub(deferred_origin);

                writeln!(
                    out,
                    "  {linker_name} ({attrs}) : ORIGIN = {:#010x}, LENGTH = {:#x}",
                    deferred_origin, deferred_length
                )
                .unwrap();
            } else {
                writeln!(out, "  /* {linker_name}: deferred, no mapping */").unwrap();
            }
        }
        // acl_only regions — skip, no linker output
    }

    out.push_str("}\n");
    out
}

fn kernel_link_script() -> String {
    r#"/* Generated by tfw — kernel linker script */
INCLUDE memory.x
INCLUDE device.x

ENTRY(Reset);
EXTERN(__RESET_VECTOR);
EXTERN(__EXCEPTIONS);
EXTERN(DefaultHandler);

PROVIDE(NonMaskableInt = DefaultHandler);
EXTERN(HardFaultTrampoline);
PROVIDE(MemoryManagement = DefaultHandler);
PROVIDE(BusFault = DefaultHandler);
PROVIDE(UsageFault = DefaultHandler);
PROVIDE(SecureFault = DefaultHandler);
PROVIDE(SVCall = DefaultHandler);
PROVIDE(DebugMonitor = DefaultHandler);
PROVIDE(PendSV = DefaultHandler);
PROVIDE(SysTick = DefaultHandler);
PROVIDE(DefaultHandler = DefaultHandler_);
PROVIDE(HardFault = HardFault_);

EXTERN(__INTERRUPTS);
PROVIDE(__pre_init = DefaultPreInit);

SECTIONS
{
  .vector_table ORIGIN(FLASH) :
  {
    __start_vector = .;
    LONG(_stack_start);
    KEEP(*(.vector_table.reset_vector));
    __reset_vector = .;
    KEEP(*(.vector_table.exceptions));
    __eexceptions = .;
    KEEP(*(.vector_table.interrupts));
  } > FLASH

  .text : ALIGN(4)
  {
    _stext = .;
    __stext = .;
    *(.PreResetTrampoline);
    *(.Reset);
    *(.text .text.*);
    *(.HardFaultTrampoline);
    *(.HardFault.*);
    . = ALIGN(4);
    __etext = .;
  } > FLASH

  .rodata __etext : ALIGN(4)
  {
    __srodata = .;
    *(.rodata .rodata.*);
    . = ALIGN(4);
    __erodata = .;
  } > FLASH

  .stack (NOLOAD) : ALIGN(8) {
    _stack_base = .;
    . = ORIGIN(STACK) + LENGTH(STACK);
    _stack_start = .;
  } > STACK

  .data : ALIGN(4)
  {
    . = ALIGN(4);
    __sdata = .;
    *(.data .data.*);
    . = ALIGN(4);
  } > RAM AT>FLASH
  . = ALIGN(4);
  __edata = .;
  __sidata = LOADADDR(.data);

  .gnu.sgstubs : {
    . = ALIGN(32);
    __veneer_base = .;
    *(.gnu.sgstubs*)
    . = ALIGN(32);
    __veneer_limit = .;
  } > FLASH

  .bss (NOLOAD) : ALIGN(4)
  {
    . = ALIGN(4);
    __sbss = .;
    *(.bss .bss.*);
    *(COMMON);
    . = ALIGN(4);
  } > RAM
  . = ALIGN(4);
  __ebss = .;

  .uninit (NOLOAD) : ALIGN(4)
  {
    . = ALIGN(4);
    __suninit = .;
    *(.uninit .uninit.*);
    . = ALIGN(4);
    __euninit = .;
  } > RAM

  PROVIDE(__sheap = __euninit);

  .got (NOLOAD) :
  {
    KEEP(*(.got .got.*));
  }

  /DISCARD/ :
  {
    *(.ARM.exidx);
    *(.ARM.exidx.*);
    *(.ARM.extab.*);
  }
}

ASSERT(SIZEOF(.got) == 0, ".got section detected — dynamic relocations not supported");
"#
    .to_string()
}

fn bootloader_link_script() -> String {
    r#"/* Generated by tfw — bootloader linker script (XIP) */
INCLUDE memory.x

ENTRY(_start);

SECTIONS
{
  .text ORIGIN(FLASH) :
  {
    _stext = .;
    *(.text.start*);
    *(.text .text.*);
    . = ALIGN(4);
    __etext = .;
  } > FLASH

  .rodata : ALIGN(4)
  {
    *(.rodata .rodata.*);
    . = ALIGN(4);
  } > FLASH

  .stack (NOLOAD) : ALIGN(8) {
    _stack_base = .;
    . = ORIGIN(STACK) + LENGTH(STACK);
    _stack_start = .;
  } > STACK

  /DISCARD/ :
  {
    *(.ARM.exidx);
    *(.ARM.exidx.*);
    *(.ARM.extab.*);
    *(.got .got.*);
    *(.data .data.*);
    *(.bss .bss.*);
  }
}
"#
    .to_string()
}

fn task_link_script(custom_regions: &[&str]) -> String {
    use std::fmt::Write;
    let mut extra_sections = String::new();
    for name in custom_regions {
        let upper = name.to_uppercase();
        writeln!(
            extra_sections,
            "  .{name} (NOLOAD) : ALIGN(4) {{\n    *(.{name} .{name}.*);\n  }} > {upper}\n"
        )
        .unwrap();
    }

    let base = r#"/* Generated by tfw — task linker script */
INCLUDE memory.x

ENTRY(_start);

SECTIONS
{
  PROVIDE(_stack_start = ORIGIN(STACK) + LENGTH(STACK));

  .text : {
    _stext = .;
    *(.text.start*);
    *(.text .text.*);
    . = ALIGN(4);
    __etext = .;
  } > FLASH =0xdededede

  .rodata : ALIGN(4)
  {
    *(.rodata .rodata.*);
    . = ALIGN(4);
    __erodata = .;
  } > FLASH

  .data : ALIGN(4) {
    . = ALIGN(4);
    __sdata = .;
    *(.data .data.*);
    . = ALIGN(4);
    __edata = .;
  } > RAM AT>FLASH

  __sidata = LOADADDR(.data);

  .stack (NOLOAD) : ALIGN(4)
  {
    . += LENGTH(STACK);
  } > STACK

  .bss (NOLOAD) : ALIGN(4)
  {
    . = ALIGN(4);
    __sbss = .;
    *(.bss .bss.*);
    . = ALIGN(4);
    __ebss = .;
  } > RAM

  .uninit (NOLOAD) : ALIGN(4)
  {
    . = ALIGN(4);
    *(.uninit .uninit.*);
    . = ALIGN(4);
    __sheap = .;
  } > RAM

  .task_slot_table (INFO) : { KEEP(*(.task_slot_table)); }
  .caboose_pos_table (INFO) : { KEEP(*(.caboose_pos_table)); }
  .hubris_abi_version (INFO) : { KEEP(*(.hubris_abi_version)); }
  .idolatry (INFO) : { KEEP(*(.idolatry)); }
  .log_strings (INFO) : { KEEP(*(.log_strings .log_strings.*)); }

"#;

    let tail = r#"
  /DISCARD/ :
  {
    *(.ARM.exidx);
    *(.ARM.exidx.*);
    *(.ARM.extab.*);
    *(.got .got.*);
  }
}
"#;

    format!("{base}{extra_sections}{tail}")
}

fn kernel_device_x(config: &AppConfig) -> String {
    use std::fmt::Write;
    // 16 standard vectors (initial SP + 15 exceptions), rest are IRQs.
    let n_irqs = (config.vector_table_size / 4).saturating_sub(16);
    let mut out = String::new();
    for i in 0..n_irqs {
        writeln!(out, "PROVIDE(Interrupt{i} = DefaultHandler);").unwrap();
    }
    out
}

fn write_file(dir: &Path, name: &str, content: &str) -> Result<(), LinkerError> {
    std::fs::write(dir.join(name), content).map_err(LinkerError::Io)
}

#[derive(Debug, thiserror::Error)]
pub enum LinkerError {
    #[error("linker script IO error: {0}")]
    Io(#[from] std::io::Error),
}
